platform :ios, '13.0'

use_frameworks!
use_modular_headers!

# Detect Flutter SDK path automatically
flutter_root = ENV['FLUTTER_ROOT']
if flutter_root.nil? || flutter_root.empty?
  flutter_root = File.expand_path('~/.flutter-sdk') if File.exist?(File.expand_path('~/.flutter-sdk'))
  flutter_root = '/usr/local/flutter' if File.exist?('/usr/local/flutter')
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  flutter_application_path = File.join('..')
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
