# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!
use_modular_headers!

# This ensures Flutter's CocoaPods integration works correctly on Codemagic
flutter_root = ENV['FLUTTER_ROOT']
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  flutter_application_path = File.join('..')
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
